name: push to eu-west-1

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Alibaba Cloud ACR
        uses: docker/login-action@v3
        with:
          registry: registry.eu-west-1.aliyuncs.com
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PWD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: true
          tags: registry.eu-west-1.aliyuncs.com/lougao-cloud/eu-west-1:${{ steps.get_version.outputs.VERSION }}
